# Doesn't work due to VPC-SC limitation
- ingressFrom:
    identityType: ANY_IDENTITY
    sources:
    - resource: projects/313022682418 # project_id: lithe-record-303112
  ingressTo:
    operations:
    - serviceName: bigquery.googleapis.com
      methodSelectors:
      - method: "*"
    resources:
    - "*"

# WORKS FINE
- ingressFrom:
    identityType: ANY_IDENTITY
    sources:
    - resource: projects/313022682418 # project_id: lithe-record-303112
  ingressTo:
    operations:
    - serviceName: storage.googleapis.com
      methodSelectors:
      - method: "*"
    resources:
    - "*"
