- ingressFrom:
    identityType: ANY_IDENTITY
    sources:
    - resource: projects/lithe-record-303112
  ingressTo:
    operations:
    - serviceName: bigquery.googleapis.com
      methodSelectors:
      - method: \"*\"
